### ISSUE TITLE
Upgrade to .NET Core 2.0

### ISSUE THREAD

**Issue by Siliconrob** [Siliconrob/CommandLine.Options#1]
Upgrade project to run on .NET Core 2.0

**Comment by NtFreX** [comment]
Do you need still help with this? I could take care of it.

**Comment by Siliconrob** [comment]
Yes, whatever you want to contribute is welcome

**Comment by NtFreX** [comment]
I've created a pull request.

**Comment by Siliconrob** [comment]
Marking #3 as addressing this issue
